config/routes.rb
Rails.application.routes.draw do
  resources :other_billing_in_agreements
  resources :software_in_agreements
  resources :device_in_agreements
  resources :agreements do
    member {get "download"}
  end
  resources :softwares
  resources :devices
  resources :device_types
  resources :customers
  resources :restaurant_evaluations
  resources :restaurant_evaluation_types
  resources :contact_people
  get 'sessions/new'

  resources :users
  resources :restaurants
  resources :companies
  resources :restaurant_types
  resources :company_types
  resources :roles

  root 'companies#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :sessions

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  get "settings" => "settings#index"

  get 'finances' => "agreements#finances"

end

app/models/agreement.rb
class Agreement < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user

  has_many :device_in_agreements, :dependent => :restrict_with_exception
  has_many :software_in_agreements, :dependent => :restrict_with_exception
  has_many :devices, through: :device_in_agreements
  has_many :software, through: :software_in_agreements

  validates :restaurant_id, presence: true
  validates :user_id, presence: true
  validates :start_date, presence: true
  validates :agreement_length, presence: true
  validates :responsible_user_id, presence: true


  def as_file
    output = [self.restaurant.name]
    output << "\n Sopimus \n"
    output << "Sopimusaika :" + self.start_date.day.to_s + "." + self.start_date.month.to_s + "." + self.start_date.year.to_s + " "+ self.end_date.day.to_s + "." + self.end_date.month.to_s + "." + self.end_date.year.to_s + "\n"
    output << "Irtisanomisaika : "+ self.term_of_notice_in_months.to_s + " kk\n"
    output << "Laskutusaika : "+self.invoicing_payment_time.to_s + "\n"
    output << "Laskutuspäivä : "+self.invoicing_date.to_s+"\n"

    if self.software.present?
      output << " Ohjelmisto "
      self.software.each {|item| output << item.name+ " " + item.software_in_agreement.monthly_price.to_s + "€/kk\n"}
    end

    if self.devices.present?
      output << "Laitteisto"
      self.devices.each do |item|
        if (item.device_in_agreement.price_is_leasing)
          output << item.device_type.name+ " " + item.device_in_agreement.monthly_price.to_s + "€/kk \n"
        else
          output << "Kertamaksu "+item.device_type.name+ " " + item.device_in_agreement.total_price.to_s + "€\n"
        end
      end
      output.join("\n")
    end
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :company_type
  has_many :contact_persons, :dependent => :destroy
  has_many :restaurants, :dependent => :destroy
  EMAIL_REGEX = /@/
  validates :email, :format => EMAIL_REGEX, :allow_blank => true
  validates :name, :presence => true
  validates :phone_number, :allow_blank => true,
            :numericality => true,
            :length => { :minimum => 10, :maximum => 15 , :message => "You made a bad number. Shame on you."}
end

app/models/company_type.rb
class CompanyType < ActiveRecord::Base
  has_many :companies, :dependent => :restrict_with_exception
  validates :name, :presence => true
end

app/models/contact_person.rb
class ContactPerson < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :company

  validates :name, :presence => true
  EMAIL_REGEX = /@/
  validates :email, :presence => true, :format => EMAIL_REGEX
  validates :phone_number,:presence => true,
            :numericality => true,
            :length => { :minimum => 10, :maximum => 15 }
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :restaurant

  validates :restaurant_id, presence: true, uniqueness: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :device_type
  has_one :device_in_agreement

  validates :device_type_id, presence: true
  validates :purchase_day, presence: true
  validates :identifier, presence: true, uniqueness: true
  validates :leasing_price, :if => :is_leased, presence: true
  validates :leasing_length, :if => :is_leased, presence: true
end

app/models/device_type.rb
class DeviceType < ActiveRecord::Base
  has_many :devices, :dependent => :restrict_with_exception
  validates :name, :presence => true
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :company, touch: true
  belongs_to :restaurant_type
  has_one :agreement, :dependent =>  :restrict_with_exception
  has_many :contact_persons, :dependent =>  :destroy
  has_many :restaurant_evaluations, :dependent => :destroy
  has_one :customer, :dependent =>  :destroy

  validates :name, :presence => true
  validates :company_id, presence: true
  EMAIL_REGEX = /@/
  validates :email, :format => EMAIL_REGEX, :allow_blank => true
  validates :phone_number, :allow_blank => true,
            :numericality => true,
            :length => { :minimum => 10, :maximum => 15 , :message => "You made a bad number. Shame on you."}
end

app/models/restaurant_type.rb
class RestaurantType < ActiveRecord::Base
  has_many :restaurants, :dependent => :nullify
  validates :name, :presence => true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users, :dependent => :restrict_with_exception
  validates :name, :presence => true
end

app/models/software.rb
class Software < ActiveRecord::Base
  has_one :software_in_agreement

  validates :name, :presence => true
  validates :identifier, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  has_many :restaurant_evaluations, :dependent => :restrict_with_exception
  has_many :agreements, :dependent => :restrict_with_exception

  attr_accessor :password
  EMAIL_REGEX = /@/
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true #password_confirmation attr
  validates_length_of :password, :in => 6..20, :on => :create


  before_save :encrypt_password
  after_save :clear_password

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.encrypted_password == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end

  def full_name
    return "#{self.first_name}" + " " + "#{self.last_name}"
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/softwares_helper.rb
module SoftwaresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_admin_right.html.erb
<% if admin_user %>
    <br>
    <h2><%= t('admin.panel')%></h2>
    <br>
    <%= link_to t('activerecord.attributes.general.destroy'), thing, method: :delete, data: { confirm: 'Are you sure?' }, :class => "deleteButton button" %>
<%end%>

app/views/shared/_agreements_container.html.erb
<%= content_for :container_menu do %>
<h2><%= t('menu.agreements')%></h2>
    <%= link_to t('agreements.index.title'), agreements_path %>
    <%= link_to t('agreements.new.title'), new_agreement_path %>
    <%= link_to t('finances.index.title'), finances_path %>
<%end%>

app/views/shared/_companies_container.html.erb
<%= content_for :container_menu do %>
<ul>
  <li><h2><%= t('menu.companies')%></h2></li>
  <li><%= link_to t('companies.index.title'), companies_path %></li>
  <li><%= link_to t('companies.new.title'), new_company_path %></li>
</ul>
    <h2><%= t('settings.company_settings')%></h2>
    <%= link_to t('activerecord.attributes.company.company_type'), company_types_path%>
<%end%>

app/views/shared/_customers_container.html.erb
<%= content_for :container_menu do %>
    <ul>
      <li><h2><%= t('menu.customers')%></h2></li>
      <li><%= link_to t('customers.index.title'), customers_path %></li>
      <li><%= link_to t('customers.new.title'), new_customer_path %></li>
    </ul>
<%end%>

app/views/shared/_device_container.html.erb
<%= content_for :container_menu do %>
    <h2><%= t('menu.devices')%></h2>
    <%= link_to t('devices.index.title'), devices_path%>
    <%= link_to t('devices.new.title'), new_device_path%>
    <h2><%= t('settings.device_settings')%></h2>
    <%= link_to t('activerecord.attributes.device.device_type'), device_types_path%>
<%end%>

app/views/shared/_restaurants_container.html.erb
<%= content_for :container_menu do %>
  <h2><%= t('menu.restaurants')%></h2>
    <%= link_to t('restaurants.index.title'), restaurants_path%>
    <h2><%= t('settings.restaurant_settings')%></h2>
    <%= link_to t('restaurants.show.restaurant_evals'), restaurant_evaluations_path%>
    <%= link_to t('activerecord.attributes.restaurant.restaurant_type'), restaurant_types_path%>
    <%= link_to t('menu.restaurant_eval_type'), restaurant_evaluation_types_path %>
<% end %>

app/views/shared/_settings_container.html.erb
<%= content_for :container_menu do %>
    <ul>
      <li><h2><%= t('menu.settings')%></h2></li>
      <li><%= link_to t('menu.software'), softwares_path %></li>
      <li><%= link_to t('activerecord.attributes.company.company_type'), company_types_path%></li>
      <li><%= link_to t('activerecord.attributes.device.device_type'), device_types_path%></li>
      <br>
      <li><h2><%= t('menu.restaurants')%></h2></li>
      <li><%= link_to t('restaurants.show.restaurant_evals'), restaurant_evaluations_path%></li>
      <li><%= link_to t('activerecord.attributes.restaurant.restaurant_type'), restaurant_types_path%></li>
      <li><%= link_to t('menu.restaurant_eval_type'), restaurant_evaluation_types_path %></li>
      <br>
      <li><h2><%= t('menu.users')%></h2></li>
      <li><%= link_to t('menu.user_details'), current_user%></li>
      <%= link_to t('menu.users'), users_path%>
      <li><%= link_to t('menu.user_role'), roles_path%></li>
    </ul>

    <br>
    <ul>
      <li><h2><%= t('menu.languages.lang')%></h2></li>
      <li><%= link_to t('menu.languages.en'), change_locale_path(:en) %></li>
      <li><%= link_to t('menu.languages.fi'), change_locale_path(:fi) %></li>
    </ul>
<%end%>