config/routes.rb
Rails.application.routes.draw do
  resources :other_billing_in_agreements
  resources :software_in_agreements
  resources :device_in_agreements
  resources :agreements do
    member {get "download"}
  end
  resources :softwares
  resources :devices
  resources :device_types
  resources :customers
  resources :restaurant_evaluations
  resources :restaurant_evaluation_types
  resources :contact_people
  get 'sessions/new'

  resources :users
  resources :restaurants
  resources :companies
  resources :restaurant_types
  resources :company_types
  resources :roles

  root 'companies#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :sessions

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  get "settings" => "settings#index"

  get 'finances' => "agreements#finances"

end

app/controllers/device_types_controller.rb
class DeviceTypesController < ApplicationController
  before_action :set_device_type, only: [:show, :edit, :update, :destroy]

  # GET /device_types
  # GET /device_types.json
  def index
    @device_types = DeviceType.all
  end

  # GET /device_types/1
  # GET /device_types/1.json
  def show
    @devices_of_this_type = Device.where(:device_type_id => @device_type.id).all
  end

  # GET /device_types/new
  def new
    @device_type = DeviceType.new
    @devices = Device.all
  end

  # GET /device_types/1/edit
  def edit
  end

  # POST /device_types
  # POST /device_types.json
  def create
    @device_type = DeviceType.new(device_type_params)

    respond_to do |format|
      if @device_type.save
        format.html { redirect_to @device_type, notice: 'Device type was successfully created.' }
        format.json { render :show, status: :created, location: @device_type }
      else
        format.html { render :new }
        format.json { render json: @device_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /device_types/1
  # PATCH/PUT /device_types/1.json
  def update
    respond_to do |format|
      if @device_type.update(device_type_params)
        format.html { redirect_to @device_type, notice: 'Device type was successfully updated.' }
        format.json { render :show, status: :ok, location: @device_type }
      else
        format.html { render :edit }
        format.json { render json: @device_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /device_types/1
  # DELETE /device_types/1.json
  def destroy
    @device_type.destroy
    respond_to do |format|
      format.html { redirect_to device_types_url, notice: 'Device type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device_type
      @device_type = DeviceType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_type_params
      params.require(:device_type).permit(:name, :warranty_length, :total_price, :leasing_price_per_month)
    end
end

app/helpers/device_types_helper.rb
module DeviceTypesHelper
end

app/views/device_types/_form.html.erb
<%= render 'shared/device_container' %>
<%= form_for(@device_type) do |f| %>
  <% if @device_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device_type.errors.count, "error") %> prohibited this device_type from being saved:</h2>

      <ul>
      <% @device_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :warranty_length %><br>
    <%= f.number_field :warranty_length %>
  </div>
  <div class="field">
    <%= f.label :total_price %><br>
    <%= f.number_field :total_price %>
  </div>
  <div class="field">
    <%= f.label :leasing_price_per_month %><br>
    <%= f.number_field :leasing_price_per_month %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/device_types/edit.html.erb
<h1>Editing Device Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @device_type %> |
<%= link_to 'Back', device_types_path %>

app/views/device_types/index.html.erb
<%= render 'shared/device_container' %>
<p id="notice"><%= notice %></p>

<h1><%= t('device_types.index.title')%></h1>

<table>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.device.device_type')%></th>
      <th><%= t('activerecord.attributes.device_type.warranty')%></th>
      <th><%= t('activerecord.attributes.device_type.tot_price')%></th>
      <th><%= t('activerecord.attributes.device_type.leas_price')%></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @device_types.each do |device_type| %>
      <tr class="navigationTable" data-type="edit" data-id="<%= device_type.id%>" data-target="device_types">
        <td><%= device_type.name %></td>
        <td><%= device_type.warranty_length %></td>
        <td><%= device_type.total_price %></td>
        <td><%= device_type.leasing_price_per_month %></td>
        <% if admin_user%>
        <td><%= link_to t('activerecord.attributes.general.destroy'), device_type, method: :delete, data: { confirm: 'Are you sure?' }, :class => "deleteButton button" %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('device_types.new.title'), new_device_type_path %>

app/views/device_types/new.html.erb
<h1>New Device Type</h1>

<%= render 'form' %>

<%= link_to 'Back', device_types_path %>

app/views/device_types/show.html.erb
<%= render 'shared/device_container' %>
<p id="notice"><%= notice %></p>
<h1><%= t('device_types.show.title')%> <%= @device_type.name %></h1>
<br>
<p>
  <strong><%= t('activerecord.attributes.device_type.warranty')%></strong>
  <%= @device_type.warranty_length %>
</p>

<p>
  <strong><%= t('activerecord.attributes.device_type.tot_price')%></strong>
  <%= @device_type.total_price %>
</p>

<p>
  <strong><%= t('activerecord.attributes.device_type.leas_price')%></strong>
  <%= @device_type.leasing_price_per_month %>
</p>
<br>
<%= link_to t('activerecord.attributes.general.edit'), edit_device_type_path(@device_type) %>
<br>
<br>
<h2><%= t('device_types.show.devices_of_type')%></h2>
<%= render 'devices/device_table', devices: @devices_of_this_type%>
<br>
<%= render 'shared/admin_right', thing: @device_type %>