config/routes.rb
Rails.application.routes.draw do
  resources :other_billing_in_agreements
  resources :software_in_agreements
  resources :device_in_agreements
  resources :agreements do
    member {get "download"}
  end
  resources :softwares
  resources :devices
  resources :device_types
  resources :customers
  resources :restaurant_evaluations
  resources :restaurant_evaluation_types
  resources :contact_people
  get 'sessions/new'

  resources :users
  resources :restaurants
  resources :companies
  resources :restaurant_types
  resources :company_types
  resources :roles

  root 'companies#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :sessions

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  get "settings" => "settings#index"

  get 'finances' => "agreements#finances"

end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :company_type
  has_many :contact_persons, :dependent => :destroy
  has_many :restaurants, :dependent => :destroy
  EMAIL_REGEX = /@/
  validates :email, :format => EMAIL_REGEX, :allow_blank => true
  validates :name, :presence => true
  validates :phone_number, :allow_blank => true,
            :numericality => true,
            :length => { :minimum => 10, :maximum => 15 , :message => "You made a bad number. Shame on you."}
end

app/models/company_type.rb
class CompanyType < ActiveRecord::Base
  has_many :companies, :dependent => :restrict_with_exception
  validates :name, :presence => true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :set_company_types, only: [:show, :edit, :new, :create, :update]
  before_action :expire_companies_table, only: [:create, :update, :destroy, :index]

  # GET /companies
  # GET /companies.json
  def index
    unless fragment_exist?('company_table')
      @companies = Company.includes(:company_type, :restaurants).all
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @users = User.all
    @restaurants_in_company = Restaurant.where(:company_id => @company.id).all
    @company_contact_people = ContactPerson.where(:company_id => @company.id).all
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    @company.added_by_user = current_user.id
    @company.edited_by_user = current_user.id
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        @company.edited_by_user = current_user.id
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

  def set_company_types
    @company_types = CompanyType.all
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :company_type_id, :street_address, :city, :country, :phone_number, :email, :added_by_user, :edited_by_user)
    end

  def expire_companies_table
    expire_fragment('companies_table')
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= render 'shared/companies_container' %>
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
    <div class="field">
      <%= f.label :company_type%>
      <%= f.select :company_type_id, options_from_collection_for_select(@company_types, :id, :name) %>
    </div>
  <div class="field">
    <%= f.label :street_address %><br>
    <%= f.text_field :street_address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/_restaurant_table.html.erb
<% if restaurants.present?%>
  <table>
    <thead>
    <tr>
      <th><%= t('activerecord.attributes.general.restaurant')%></th>
      <th> <strong><%= t('activerecord.attributes.general.street_address')%></strong></th>
      <th><strong><%= t('activerecord.attributes.general.city')%></strong></th>
      <th><strong><%= t('activerecord.attributes.general.country')%></strong></th>
      <th><strong><%= t('activerecord.attributes.general.phone_number')%></strong></th>
      <th><strong><%= t('activerecord.attributes.general.email')%></strong></th>
      <th>Server ip</th>
      <th><%= t('activerecord.attributes.restaurant.restaurant_type') %></th>
    </tr>
    </thead>

    <tbody>
    <% restaurants.each do |restaurant| %>
        <tr class="navigationTable" data-target="restaurants" data-id="<%= restaurant.id%>">
          <td><%= link_to restaurant.name, restaurant %></td>
          <td><%= restaurant.street_address %></td>
          <td><%= restaurant.city %></td>
          <td><%= restaurant.country %></td>
          <td><%= restaurant.phone_number %></td>
          <td><%= restaurant.email %></td>
          <td><%= restaurant.server_ip %></td>
          <td><%= restaurant.restaurant_type.name %></td>
        </tr>
    <% end %>
    </tbody>
</table>
<%end%>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'shared/companies_container' %>
<h1><%= t('companies.index.title')%></h1>
<br>

  <table>
    <% @companies.each do |company| %>
    <thead>
      <tr>
        <th><%= t('activerecord.attributes.general.name')%></th>
        <th> <strong><%= t('activerecord.attributes.company.company_type')%></strong></th>
        <th> <strong><%= t('activerecord.attributes.general.street_address')%></strong></th>
        <th><strong><%= t('activerecord.attributes.general.city')%></strong></th>
        <th><strong><%= t('activerecord.attributes.general.country')%></strong></th>
        <th><strong><%= t('activerecord.attributes.general.phone_number')%></strong></th>
        <th><strong><%= t('activerecord.attributes.general.email')%></strong></th>
      </tr>
    </thead>

    <tbody>
        <tr data-id="<%= company.id%>" data-target="companies" class="navigationTable">
          <td><%= link_to company.name, company %></td>
          <td><%= company.company_type.name %></td>
          <td><%= company.street_address %></td>
          <td><%= company.city %></td>
          <td><%= company.country %></td>
          <td><%= company.phone_number %></td>
          <td><%= company.email %></td>
        </tr>
        <tr>
          <td colspan="7"><%= render 'restaurant_table', restaurants: Restaurant.where(:company_id => company.id).all %></td>
        </tr>
    </tbody>
    <% end %>
  </table>

<br>
<%= link_to t('companies.new.title'), new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>
<%= render 'shared/companies_container' %>
<h1><%= @company.name %></h1>
<br>
<table class="smallTable">
  <thead>
  <tr>
    <th><strong><%= t('activerecord.attributes.company.company_type')%></strong></th>
    <th><strong><%= t('activerecord.attributes.general.street_address')%></strong></th>
    <th><strong><%= t('activerecord.attributes.general.city')%></strong></th>
    <th><strong><%= t('activerecord.attributes.general.country')%></strong></th>
    <th><strong><%= t('activerecord.attributes.general.phone_number')%></strong></th>
    <th><strong><%= t('activerecord.attributes.general.email')%></strong></th>
    <th><strong><%= t('activerecord.attributes.company.added_by_user')%></strong></th>
    <th><strong><%= t('activerecord.attributes.company.edited_by_user')%></strong></th>
    <th colspan="1"></th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= @company.company_type.name %></td>
    <td> <%= @company.street_address %></td>
    <td><%= @company.city %></td>
    <td> <%= @company.country %></td>
    <td><%= @company.phone_number %></td>
    <td><%= @company.email %></td>
    <td><%= @users.find_by_id(@company.added_by_user).full_name %></td>
    <td><%= @users.find_by_id(@company.added_by_user).full_name %></td>
    <td><%= link_to 'Edit', edit_company_path(@company) %></td>
  </tr>
  </tbody>
</table >
<%= render 'contact_people/contactPeople_table', contact_people: @company_contact_people %>
<%= link_to t('contact_people.new.title'), new_contact_person_path(:company_id => @company.id) %>
<br>
<br>
<p>
  <strong><h2><%= t('companies.show.restaurants_in_company')%></h2></strong>
</p>
<%= render 'restaurant_table', restaurants: @restaurants_in_company %>
<br>
<%= link_to t('restaurants.new.title'), new_restaurant_path(:company_id => @company.id) %>
<br>
<%= render 'shared/admin_right', thing:@company %>